* DONE Bible heroes in video games // Ninjas make way for Noah and Moses on Christian tapes (AM head varies) 
Jeffrey Brody
The Orange County Register 
269 words
19 March 1991
The Orange County Register
OCR
English
© 1991 Orange County Register.  Provided by ProQuest Information and Learning.  All rights reserved.  

You've read The Book. Now play the video game. 

Wisdom Tree, a Christian-owned entertainment company in Brea, has come up with Bible Adventures, a video alternative to Nintendo games. 

Instead of blasting Ninja warriors or zapping shady drug dealers on the video screen, children can help Noah gather animals into the ark and save baby Moses from Pharaoh's soldiers. 

Mike Wilson, a former Sunday-school teacher and vice president of Wisdom Tree, came up with the concept after watching students pay more attention to video games than the Bible. 

"I felt helpless and pretty much at the mercy of these games," Wilson said, "because that's what kids are interested in and excited about. This gives kids a wholesome alternative to the sorcery and violence." 

Wisdom Tree has sold 30,000 casettes featuring three games -- Noah's Ark, Save Baby Moses and David and Goliath -- since Christmas. The suggested retail price is $39.95, Wilson said. 

Ward Fredine, 7, of Garden Grove said the Biblical games are as much fun as Super Mario Brothers. 

"We bought them for the kids," said Steve Fredine, Ward's father, "because we were tired of the slash-someone's-face-off, death-and-destruction type video games." 

Brian Stonehill, a media specialist at Pomona College, said he's not surprised. 

"The essence of the Protestant Reformation was to translate the Bible into the vernacular," Stonehill said. "Video games are clearly the vernacular of our day."  

Document ocr0000020011109dn3j00c0r
* DONE Nintendo fans can learn Bible stories while zapping bad guys 
Adelle M. Banks 
KNIGHT-RIDDER TRIBUNE NEWS SERVICE
317 words
6 April 1991
Austin American-Statesman
AAS
FINAL
E3
English
© 1991 Austin American Statesman.  Provided by ProQuest Information and Learning.  All Rights Reserved.  

Move over, Mario. A California-based Christian company is zapping Bible adventures into video games. 

Nintendo zealots now can blip some bad guys and at the same time learn the Bible stories of Noah, baby Moses and David and Goliath. 

The game, Bible Adventures, is the brainchild of Mike Wilson, vice president of Wisdom Tree. It is played on the Nintendo system. 

He says he came up with the idea when he had trouble teaching Sunday school: His students were staying up until midnight playing Nintendo rather than studying their Bible lessons. 

"I just wanted to develop something that was adventuresome as well as exciting, but at the same time had a lot of different moral issues that could pretty much mold their personality," Wilson says. 

In the first part of the game, a bearded Noah picks up animals during his trek through the forest and guides them to the ark before the 40-day flood. 

Noah is followed by the "Baby Moses" game in which the joystick controller plays Moses' mother, helping him escape after Pharaoh ordered all male Hebrew children drowned. 

In the David and Goliath sequence, the player has to hit Goliath between the eyes using a sling and five smooth stones. 

As each adventure continues, Bible verses appear on the screen. 

Turning the biblical characters into video heroes apparently requires a high degree of Nintendo mastery. Only at the top level of the adventures does the player get to fill the ark, save baby Moses or fight Goliath. 

While it's possible for Noah to fail and for baby Moses to be captured by soldiers, no one reached at Wisdom Tree who has played the game knows exactly what happens if David's aim is off against Goliath. They haven't reached that level.  

Document aas0000020011108dn46009ka
* DONE The Word on Bible video game: It's a hit // Creator says playing Noah, `slaying' Goliath make learning an adventure 
Neal Gendler; Staff Writer 
329 words
24 April 1991
Star-Tribune Newspaper of the Twin Cities Mpls.-St. Paul
MSP
METRO
03B
English
(Copyright 1991) 

Perhaps it was predestined: The Good Book has become a video game. 

Frustrated by his Bible students' preference for Nintendo over homework, a California electronic games salesman,  Mike Wilson, created a three-game cartridge to teach Nintendo enthusiasts about the Bible. 

In Bible Adventures, characters move through 12 "worlds" of increasing difficulty for a heroic purpose. Noah builds the ark and gathers animals and food; baby Moses is rescued; David slays Goliath. That's as close as Bible Adventures comes to video-game violence. 

"God impressed it upon my heart to look into developing something that would be more wholesome . . . that would be able to mold the character of young people," Wilson said. His programmers develop the games; he makes sure they are biblically accurate.  The games started selling this year in religious bookstores, including several in the Twin Cities, and "are doing real well in the Christian market," he said. The cartridge lists for $39.95. 

The games, which use a format similar to the Super Mario game series, offer novelty in each use and high involvement. Players can assume the role of David or Noah or baby Moses' sister. 

Characters climb, jump, run, "do almost anything a normal person can do," Wilson said. "You can never die in our games, but if you don't complete the level before you run out of health or strength, you have to start over." 

Just as Mario can grab magic flowers and mushrooms to gain strength, a Bible Adventures player can reach pellets that flash Bible quotes onto the screen and prolong playing time. 

Wilson plans to bring out three more cartridges by the end of the year. "We treat it as a ministry," he said. Players "are experiencing electrifying adventure, but at the same time they're learning wisdom and the word of God." 

* DONE Players score spiritual points in video games of Bible stories 

KNIGHT-RIDDER NEWS SERVICE
257 words
26 May 1991
Austin American-Statesman
AAS
FINAL
A12
English
© 1991 Austin American Statesman.  Provided by ProQuest Information and Learning.  All Rights Reserved.  

DETROIT - It is written that if a child helps Miriam carry her brother, the baby Moses, past enough soldiers, pools of water and spiders, Moses will be rescued - and the child will earn bonus points. 

So goeth Bible Adventures, a Nintendo cartridge game created by the Brea, Calif., company Wisdom Tree as a spiritual alternative to such punch-'em-out, shoot-'em-up Nintendo fare as Super Mario Brothers and Teenage Mutant Ninja Turtles. 

Instead of saving a princess or battling ghosts, the Bible Adventures player also couples up animals on Noah's Ark and assists David in aiming his slingshot at Goliath's forehead. Between each level, the screen displays one of 100 Bible verses. 

"A lot of fantasy games involve witchery, sorcery, villains," said Darryl Beamon, a spokesman for Wisdom Tree. "Many of these games are very anti-Christian, anti-religious . . . and a lot of our children are being lobotomized by all this." 

Beamon said the company has sold more than 30,000 cartridges, at a suggested retail price of $39.95. And while most buyers have been age 6 to 12, Beamon says, nearly one in five users are ages 36 to 50. 

This summer, Wisdom Tree plans to offer a Spanish-language version of Bible Adventures and a new game called King of Kings that features Jesus as a baby receiving gifts from the Three Wise Men, traveling with his parents and admonishing the elders in a temple.  

Document aas0000020011108dn5q00ezd

* DONE Children can take part in biblical adventures and read Bible   
1,216 words
1 June 1991
The Toronto Star
TOR
SA2
K13
English
Copyright (c) 1991 The Toronto Star   

Children can take part in biblical adventures and read Bible verses with a new Nintendo cartridge game, Knight-Ridder News Service reports.   

For example, if a child helps Miriam carry her brother, the baby Moses, past enough soldiers, pools of water and spiders, Moses will be rescued - and the child will earn bonus points.   

So goeth Bible Adventures, a game created by the Brea, Calif., company Wisdom Tree as a spiritual alternative to such punch-' em-out, shoot-'em-up Nintendo fare as Super Mario Brothers and Teenage Mutant Ninja Turtles.   

Instead of saving a princess or battling ghosts, the Bible Adventures player also couples up animals on Noah's Ark and assists David in aiming his slingshot at Goliath's forehead. Between each level, the screen displays one of 100 Bible verses.   

"A lot of fantasy games involve witchery, sorcery, villains," says Darryl Beamon, a spokesperson for Wisdom Tree. "Many of these games are very anti-Christian, anti-religious . . . and a lot of our children are being lobotomized by all this."   

Wisdom Tree plans to offer a Spanish-language version of Bible Adventures and a new game called King of Kings that features Jesus as a baby receiving gifts from the three wise men, travelling with his parents and admonishing the elders in a temple.   

* The gospel according to MTV: Videos and computer games transport Bible into 21st century 
Peggy Landers 
KNIGHT-RIDDER NEWS SERVICE
815 words
15 August 1992
Austin American-Statesman
AAS
FINAL
D4
English
© 1992 Austin American Statesman.  Provided by ProQuest Information and Learning.  All Rights Reserved.  

Jesus is duded up in a Don Johnson-esque T-shirt-and-jacket combo. The guy possessed by demons wears a baseball cap. The demons have their own cable channel. 

And the music, well, that all depends on which version of Out of the Tombs you get. The American Bible Society's MTV-like video of Mark 5:1-20 comes two ways. 

"There's a chant version and a rap version," says Eugene Habecker, president of the nondenominational Bible society that publishes, distributes and translates Bibles. 

It's one thing to translate the Bible into Urdu, but this - filming Jesus in hand-to-hand combat on a fire escape with a shirtless, drooling man with bad teeth, putting it to rap music, then editing it into quick, rhythmic scene bites - is quite another. The video-ization of the Gospel story is by far the most daring project the ABS has tackled. It should be available in stores this fall. 

"Some people ask, `What does the Bible have to do with MTV?' " says Habecker. "My point is that it has everything to do with MTV." 

The ABS' goal, he says, is to reach teen-agers more apt to flip TV channels than book pages. And Out of the Tombs is just one way that Bible lore has gone high-tech in the past two years. 

Check it out: 

- Wisdom Tree, a Brea, Calif., company, has sold more than 300,000 Nintendo-compatible video Bible games since it introduced four programs less than a year ago. PC and GameBoy versions will be available by Christmas. 

- An interactive Bible adventure game called Where in the Word is Amaz'n Blaz'n? will be introduced in September by Navpress of Colorado Springs. 

- Christian singer Carman's Resurrection Rap, on his music video Revival in the Land ($12.95 at most Christian book stores), shows Jesus as the leader of a Christian street gang, wearing jeans and leather jacket. 

Music videos, video games and interactive software are "a new angle and a growing trend," says William Anderson, president of the 3,500-member Christian Booksellers' Association. Video sales and rentals account for about 3 1/2 percent of the $2 billion Christian products industry, Anderson says. "Software is so new we're not tracking it separately yet, but we will." 

Says ABS president Habecker:"As we move into the 21st century, television has become the dominant medium. It's the way people learn. We need to take the message of the Scripture and put it in a format and a language that people can understand. We need to take away all the excuses for not reading the Bible." 

That will not be an easy job, Habecker concedes. Despite the Bible society's efforts to make the Good Book accessible - it publishes a Bible in contemporary English, a Bible in Braille, and will soon produce a signing Bible on video for the deaf - accessibility is a tough mission in secular times. 

Few members of the more than 90 percent of U.S. households who own a Bible actually read it, according to the Barna Research Group, a California polling organization. Only one in 10 Americans claims to read the Bible daily; fewer than one in 30 people younger than 25 read it every day. 

Only half the people who said they believed the Bible was the word of God in a 1990 Gallup poll could name one of the four gospels. Many did not know who preached the Sermon on the Mount. (Jesus preached it.) 

Not everyone embraces the new media for the Good Book. "It is controversial because you have Christians who believe Bible stories should be portrayed exactly as they are described," says Roger Van Fleet, who sells and rents Biblical video games and high-tech Christian music videos at the Bible Book Store in North Miami, Fla. 

"But I tell them there are people who have a hard time identifying with some guy in long hair and a beard, wearing a nightgown. Jesus called us to be fishers of men. I say we're just baiting the hook in a different way." 

Ira Dotson, an account executive at Wisdom Tree, agrees. "Some Christians have a problem with the medium of Nintendo, because they feel . . . the graphic violence of some Nintendo games has a negative effect on the family. But we say kids are going to play Nintendo regardless. Let's give them an alternative." 

One alternative is Bible Adventures ($44.95, for ages 5 to 8), which includes three action-oriented Old Testament games - "Noah's Ark," "Save Baby Moses" and "David and Goliath." Wisdom Tree's games for older players, such as "Exodus," include scriptural questions with extra points for correct answers.  

* Interactive Bible Designed To Appeal To Nintendo -MTV Generation 

MICHAEL A. GIARRUSSO 
522 words
15 August 1992
The Associated Press
ASP
English
(Copyright 1992.  The Associated Press.  All Rights Reserved.) 

ATLANTA (AP)  -  Teen-agers who can't understand Matthew, Mark, Luke or John might learn more from the Gospel according to In Effect, a rap group. 

The New York rappers are featured in an interactive computer program that translates Bible stories into language and images appealing to teen-agers, but not necessarily to their parents. 

"We wanted it to hit young people with the same kind of impact the story had in the first century," said Fern Lee Hagedorn, the American Bible Society's director for multimedia translations. 

People used to act out Bible stories before the print version became widely available, Ms. Hagedorn said. "We wanted to recapture the orality of the text." 

The society, a non-profit organization that has representatives from more than 100 Christian denominations, came up with a version of Mark 5:1-20 that would be at home on MTV. 

"Our intention was to reach teen-agers, specifically juniors and seniors in high school," Ms. Hagedorn said. 

A team of Bible scholars chose Mark 5:1-20 from a group of four stories because teen-agers surveyed said it is one of the most difficult New Testament selections to understand, Ms. Hagedorn said. 

In it, Jesus Christ meets a man possessed by demons who hits himself with stones. Jesus exorcises the demons, which then possess hundreds of pigs. The pigs run into the sea and drown. 

The computer version includes text and audio that explain the verses as well as explanations of anachronistic biblical terms. To demonstrate the meaning of a word in the first century, two teen-agers describe what some modern words  -  including some foul ones  -  mean to them. 

The cursing, rap music and sometimes violent images, including a possessed man who foams at the mouth as he hits himself, did not dissuade the Bible society's board of directors. 

"One board member said, `Remember, if we don't like this, then the kids probably will,"' said Gary Rowe, senior vice president of Turner Educational Services in Atlanta, which helped get the project off the ground. 

The prototype, which is not for sale, was produced by the Atlanta software company Floyd Design and shown to focus groups of teen-agers in Atlanta, Boston and Kansas City. 

"It helped me learn more easily," said Deirdre Haynes, 15, who saw it in her Sunday school class in the Atlanta suburb of Roswell. "I couldn't understand the verse when I just read it out of the Bible." 

The software requires a laserdisc player, an IBM-compatible computer and a color monitor. For people without computers, portions of the Bible project will be available on videotape with a study guide. 

It took about nine months to design the software, said Reg Pettus, a former partner at Floyd Design. He now has his own company, Pettus Media and Design, which will produce future programs. 

New programs will be produced more quickly  -  although it could take decades to do the whole Bible, Pettus said. He said he hopes the price will be less than $200 a program. 

* Video fans still prefer Nintendo to Jesus 

Rick Ansorge; Gazette Telegraph 
345 words
22 August 1992
Colorado Springs Gazette Telegraph
CSP
E1
English
(Copyright 1992) 

David slays Goliath in the "Bible Adventures"  video game, but it looks like it'll be a while before he slays the Super Mario Brothers. 

Even in Colorado Springs households that have embraced such Christian video games, secular video games still outnumber their sacred competitors. 

"We have 12 Nintendo games and only two Bible games,"  says Darlene Daffron, who has four sons, ages 12-20. 

"The Bible games are not as fast-paced, the graphics are not as good, and they're more challenging than other games because you have to answer questions to get to a certain level." 

But the games are entertaining, too. "Spiritual Warfare,"  for instance, requires players to fend off gangs, terrorists and crooked cops. 

The video games' prices - $35-$45 - have kept them from catching on, according to one local retailer. 

"We sell maybe five a week," says Sonya Hollingsworth, a senior sales associate at Family Bookstore. "Little kids see 'em and want 'em, but when their parents see the price,  they say no." 

Nintendo games cost as little as $15. 

But Hollingsworth and retailers at Focus on the Family's bookstore and the Lord's Vineyard Christian Supply - say computerized defenders of the faith will catch on. 

"Parents, especially Christian parents, like to see their kids go for something with spiritual significance," says Lord's Vineyard co-owner Jeff Pederson. 

Pederson estimates he's sold 200 to 300 of the games since they were introduced in 1990. 

This fall he plans to sell two new games: "Joshua and the Battle of Jericho" and a Game Boy-compatible version of "Exodus." 

Old Testament games are better sellers than New Testament games, he says, because they're more action-packed. 

One New Testament game - "King of Kings: The Early Years"  - had a manger scene on its cover, but people found it "too Christmasy," Pederson says. 

Sales picked up, he says, after the manufacturer issued a new cover showing a warrior on camelback, charging through the desert. 

Label: RELIGION SIDEBAR

Document csp0000020011107do8m008m9


* Technological conversions: Christians aim messages through electronic mediums 

Torri Minton 
594 words
23 October 1992
Austin American-Statesman
AAS
FINAL
D4
English
© 1992 Austin American Statesman.  Provided by ProQuest Information and Learning.  All Rights Reserved.  

A leather-jacketed thrash rocker bursts through a paper window as fans dive into each other. A crowd smashes guitars onstage while the group's "lead screamer," wearing a cross on a chain in his ear, screams, "Smash, smash, smash the guitar!" 

Later, a singer with the band, One Bad Pig, admits, "We like to go wild . . . but we're always gonna give 'em the gospel." 

In another music video, heavy-metal musicians prance onstage with striped guitars, wearing skintight pants and thick eye makeup. A cross flashes in the background in time to the crashing beat and the flipping of fluffy hair. 

"Jesus makes me want to sing," yells the singer with the group, Stryper. 

In another, three "rap, rock and soul" musicians with DC Talk, in hooded sweatshirts, baggy pants and baseball caps, step through urban streets, rapping as large crosses dance on their necks: "God is doing a `nu thang.' " 

It's loud. It's punk. It's metal. It's Christian. 

It's the avant-garde of a new wave of thoroughly modern video Christianity, which includes screaming punkers for Jesus, Bible-story Nintendo games, Bible software and MTV-esque productions with an electric Jesus in jeans. 

Video is the fastest-growing segment of the $2 billion Christian-products industry, says Bill Anderson, president of the 3,500-member Christian Booksellers' Association. 

Florida-based ZTV plans to launch a national 24-hour Christian music-video television station in the next few weeks. The cable show will play music including heavy metal, rap and gospel. 

More than 2 million copies - worth more than $29 million, retail - of a series of Hanna-Barbera cartoon Bible videos for children have sold in the past five years. 

Wisdom Tree of Brea, Calif., has sold 350,000 Nintendo-compatible Bible video games with scripture quotes and Bible questions since January 1991. 

Another game, Joshua, in which the prophet leads God's people into the land of promise with weapons like the horn of Jericho and God speed, is due out this month. Video sales, particularly children's, have doubled in the past five years and now make up 3 percent of the vast Christian products industry, says the Christian Booksellers' Association, based in Colorado Springs. 

And that doesn't include Bible software, still too new to be counted - everything from personal ministry managers to a word-search computer Bible. 

The Lord has not gone high-tech without controversy. 

Some Christians insist that Bible stories should be presented only exactly as they are described. Others simply don't like video games. 

Rock 'n' roll evangelism? Not, others say, citing the biblical injunction to "refrain from the appearance of evil." 

Some Christian bookstores either refuse to carry the rock videos or stash the music quietly behind the counter. 

The most cutting-edge video at Nav Press, a Christian books, video and software publisher in Colorado Springs, is something called "Edge TV," started last fall. 

It's a quarterly magazine-format production with music, dancing and discussions of topics its promoters say are new to the Christian video market, such as eating disorders, child abuse and sexual choice. 

There have been complaints. "Edge" doesn't give kids answers, say Christians used to adhering to very specific values. But the idea is to challenge, and get kids to think, says Susan Pannell, a Nav Press spokeswoman.  

PHOTO; Caption: One Bad Pig is among the groups that will deliver `rock 'n' soul' on a Christian rock video cable channel. 

Document aas0000020011106doan00w3e


* Playing with TV heroes

By Gordon Webb. 
342 words
13 December 1992
The Sunday Times
ST
English
© 1992 Times Newspapers Ltd. All rights reserved 

Nintendo and Sega are the undoubted leaders in video games, but they could be displaced soon by compact disc-based interactive games.

Philips and Amiga launched #500-plus systems this year and many others are working on more competitively priced products for next year.

The Philips CD-1 (#499.99) simply plugs into existing hi-fi and TV systems. The machine allows users to interact with whatever is on the screen. For example, it is possible for children to talk to their friends in Sesame Street.

The system comes with a thumbstick controller but a panel of tracker balls, which is easier for nursery-age children to use, can be added. It can be used to play conventional musical CDs as well, but most intriguingly, via a Kodak service, it is possible to have camera film processed on to a CD disc to play back snapshots on a TV screen. Because the pictures are digitally encoded, the quality is outstanding, making it possible to zoom in, rotate the image or view any part of the photograph in more detail.

The Commodore Amiga system (also priced at #499.99) plays "multi-media" CDs. These discs combine audio, video, graphics, text and animation and cover a wide range of topics and subjects. On the entertainment side there is a flight simulator and conventional board games, such as chess and draughts, with digitised speech and sound effects.

Educational programs teach spelling and basic arithmetic, allow the viewer to read Shakespeare and the Bible and can teach users how to play music on electronic keyboard instruments.

There is something to rejuvenate the jaded video-game user, too. Hornby has launched a system called Game Genie for enhancing existing Nintendo Entertainment System games. It is a pack into which the game is slotted before both are inserted in the game deck. A book of codes tells the players how to increase their lives and firepower, run faster, explore all levels of play and introduce other special effects. 

Document st00000020011123docd004no

* Holy Warfare Games Offer Wholesome Alternative 

Cathy Mong DAYTON DAILY NEWS 
517 words
8 October 1994
Dayton Daily News
DDNW
CITY
6C
English
(Copyright 1994) 

Sharon Pottinger watched approvingly as her 13-year-old son, John, tried his hand at Spiritual Warfare. 

Young Pottinger, a student at Carlisle Junior High School, was attempting, via video game, to collect the Full Armor of God while avoiding the pitfuls of modern man. 

The game, manufactured by Wisdom Tree Inc., of Brea, Calif., is one of a burgeoning number of Christian-based videos that have become an alternative to violent games. These Bible-based games are appealing to kids and agreeable to many parents. 

"I think it's great," Mrs. Pottinger said. "It's an alternative to things the world has to offer." 

Spiritual Warfare, for play on Game Boy; and Joshua and the Battle of Jericho, for play on Sega Genesis, bring Wisdom Tree's video offerings to 19. Prices range from $24.95 for use on Game Boy to $64.95 for play on Super Nintendo. 

Some videos have come under fire in recent months for containing gruesome animation, including ripping off heads of opponents or pulling out the spinal cord. 

In Spiritual Warfare, the player encounters obstacles and answers Bible questions. 

"It's a Pilgrim's Progress format brought into modern life," says Brenda Huff, sales supervisor at Wisdom Tree. 

"We're in an electronic age and you have to meet the kids where they're at," Huff said. "You can't just say 'no, you can't do it.' You have to give them an alternative that's wholesome." 

Social concepts are stressed in the Bible-based games, be it in saving souls or feeding the poor. 

In an earlier video game, Bible Buffet, players attempt to feed the hungry by feasting on God's word. "The object is to collect for a food bank," Huff said. 

Huff said the company, in business since 1991, sells its products primarily to Christian bookstores. Total sales range between $500,000 and $750,000. 

She said the company hopes to release a "super 3-D Noah's Ark" around Thanksgiving. 

According to Huff, these videos are challenging and fun. "If kids didn't like them, you couldn't force them to use these. And they really like them." 

According to Brad Balsmeyer, receiving supervisor at the Dayton Mall Family Bookstore, the videos tempt not only the youngsters but salvation-minded adults. 

"They really get into it, especially when they're working out of a tight situation," he said. 

Huff agreed. "It's for everybody. We sell for 4- to 5-year-olds to grandparents who call us and tell us they love to play it by themselves." 

BOX} -------------------------------------------------------------------- ---- 

HOW TO BUY 

What: Christian videos games manufactured by Wisdom Tree Inc., Brea, Calif. 

Where available: Family Bookstores, Dayton Mall. 

Why: Offers parents and children an alternative to violent video games. 

Cost: $24.95 to $64.95. -------------------------------------------------------------------- ---- 

PHOTO:  Above, 13-year-old John Pottinger plays a Christian video game at the Family Bookstores at the Dayton Mall; at left, Spiritual Warfare is for play on Game Boy PHOTO CREDIT: BILL GARLOW/DAYTON DAILY NEWS 

Document ddnw000020011030dqa8002yn


* To Unleash God's Wrath Press A,B,C: Christian Video Games Scoring 

By BERNIE MIXON and MICHAEL A. LEV, Special from the Chicago Tribune 
981 words
24 February 1995
The Record
REC
English
© 1995 North Jersey Media Group Inc. Provided by ProQuest Information and Learning. All rights reserved.  

To rescue heroes imperiled by villains in the make-believe world of video games, most kids would call on laser-guided missiles or at least a well-placed karate kick. 

Twelve-year-old Antoine Babicz turns to an arsenal of Bible questions. Answering them gets Moses out of a jam and shows the Egyptians a thing or two. 

Like countless adolescent boys, Antoine is enamored of his Gameboy machine, but he loads it with a game called Exodus instead of the Super Mario Brothers. 

In another barometer of shifting popular culture, Exodus and other games such as Super 3-D Noah's Ark are part of an emerging niche of Christian video toys and action figures that are being marketed to parents fed up with Hollywood sex and violence. 

"I like action and adventure, and this is like going on an adventure in the Bible," Antoine said. "You get to go through mazes with Moses and fight the Egyptians with the Word." 

After the dust settles in other games, the ultimate aim is to be the only one left standing. Antoine seeks treasures of holy oil, the armor of God, and greater faith. In Super 3-D Noah's Ark, players must regain order in the ark using food as a lure. 

The games join the more established Christian book, gift, and rock-music industries, which have been expanding for more than a decade. The Christian book market, for example, has grown to a nearly $3 billion industry last year from $1 billion in 1980, according to the Christian Booksellers Association. 

Bill Anderson, president of the CBA, said the growing interest in Christianity and family values will draw more parents to the market. 

"We are seeing an increasing number of baby boomers _ churched as well as unchurched _ coming into the stores looking for products to help them instill in their children qualities like honesty, integrity, respect for authority _ things based in the Scriptures," he said. 

The new action figures include the Holyland Heroes, five different sets depicting stories from the Old Testament. There's Samson and a Philistine; David and Goliath; Judas Maccabaeus and a Syrian warrior; Moses and Ramses II; and Joshua and a Canaanite. 

"We are hoping to use the Old Testament in a very sober and wise way," said David Pagani, president of Vermont-based New Ventures, which markets Holyland Heroes. "Action figures are so dominant in play patterns of young children right at the time they are supposed to be open to new ideas." 

"Parents don't have to worry about the content of these games," said Debbie Lund, general manager of Wisdom Tree of Brea, Calif., which manufactures Christian video games for use with the Nintendo and Sega Genesis systems. 

Some of the titles include "King of Kings," "Bible Buffet," and "Bible Adventures." The newest game is Sunday Funday _ the Ride, that gets kids excited about Sunday School and includes a karaoke section. 

While parents remain the largest chunk of Christian video game purchasers, the user market is not just relegated to children. Adults, some in their 60s and 70s, have placed orders for the games, Lund said. 

There aren't any statistics on the size or growth of the Christian toy market, though it's clearly grown considerably since the first board games appeared in Christian bookstores about 15 years ago. 

However, Dick Malone, a vice president at Spring Arbor Distributors, a Michigan distributing house, said market growth is hemmed in by a limited repertoire of potential games. 

"After somebody has toy figures for Noah's Ark, how many more do you want your kids to have?" he asked. 

And at least one Christian educator says the proliferation of Bible-based toys is doing more harm than good. 

"That kind of stuff is what's wrong with Christianity right now," said Perry G. Downs, director of the doctor of education program at Trinity Evangelical Divinity School in Deerfield, Mich. 

"When you take what we say is the word of God and trivialize it into a video game you teach disregard, rather than regard, for the word of God," Downs said. 

"The Christian industry tends to mirror what is going on in the secular industry," said John Chrastka, book buyer at Logos Bookstore of Oak Park, Ill. He calls the toy revolution the "Christianization of mainstream media." 

For the past 10 years, Elgin, Ill.-based Rainfall Toys has marketed action figures, preschool toys, activity toys, puzzles, games, dolls, play sets, and videos. 

Wal-Mart will carry the Holyland Heroes line in its Illinois stores to test the waters before carrying them nationwide. The figures will be available around Easter, said Keith Morris, spokesman for Wal-Mart. 

Paul and Vanessa Babicz carefully scrutinize toys their kids play with to make sure they are in line with the couple's Pentecostal beliefs. 

There wasn't much of a selection of video games to satisfy Antoine's yearning for adventure without violence until Christian video games came on the market. 

"This is a great alternative," Paul Babicz said. "There's so much junk out there, stuff totally against our beliefs." 

But critic Downs said the reason for the toy boom comes down to pure economics. 

"I do think it is another form of marketing Jesus, marketing Christianity," Downs said. "It is part of why Christianity is becoming increasingly marginalized in our society." 

Vanessa Babicz does not agree. 

"If we want kids to stay in line with the way we've raised them, then we have to compete with what the world is putting out there," she said. 

"As Christian parents, we have to find ways to keep kids going the right way," she said. "Kids can have fun and keep God in it."  

Document rec0000020011026dr2o008kr


* Religious Figures Do Battle in Video Game World 

Bernie Mixon and Michael A. Lev Chicago Tribune 
792 words
26 February 1995
Los Angeles Daily News
LAD
English
© 1995 Los Angeles Daily News.  Provided by ProQuest Information and Learning.  All rights reserved.  

To rescue heroes imperiled by villains in the make-believe world of video games, most kids would call on laser-guided missiles or at least a well-placed karate kick. 

Twelve-year-old Antoine Babicz turns to an arsenal of Bible questions. Answering them gets Moses out of a jam and shows the Egyptians a thing or two. 

Like countless adolescent boys, Antoine is enamored of his Gameboy machine, but he loads it with a game called Exodus instead of the Super Mario Brothers. In another barometer of shifting popular culture, Exodus and other games such as Super 3-D Noah's Ark are part of an emerging niche of Christian video toys and action figures that are being marketed to parents fed up with Hollywood sex and violence and ready for value in toys beyond the price tag. 

"I like action and adventure, and this is like going on an adventure in the Bible," Antoine said. "You get to go through mazes with Moses and fight the Egyptians with the Word." 

After the dust settles in other games, the ultimate aim is to be the only one left standing. Antoine seeks treasures of holy oil, the armor of God and greater faith. In Super 3-D Noah's Ark, players must regain order in the ark using food as a lure. 

The games join the more established Christian book, gift and rock-music industries, which have been expanding for more than a decade. The Christian book market, for example, has grown to a nearly $3 billion industry last year from $1 billion in 1980, according to the Christian Booksellers Association. 

"We are seeing an increasing number of baby boomers - churched as well as unchurched - coming into the stores looking for products to help them instill in their children qualities like honesty, integrity, respect for authority - things based in the Scriptures," said Bill Anderson, president of the CBA. 

The new action figures include the Holyland Heroes, five different sets depicting stories from the Old Testament. There's Samson and a Philistine, David and Goliath, Judas Maccabaeus and a Syrian warrior, Moses and Ramses II, and Joshua and a Canaanite. 

"We are hoping to use the Old Testament in a very sober and wise way," said David Pagani, president of Vermont-based New Ventures, which markets Holyland Heroes. "Action figures are so dominant in play patterns of young children right at the time they are supposed to be open to new ideas." 

"Parents don't have to worry about the content of these games," said Debbie Lund, general manager of Wisdom Tree of Brea, which manufactures Christian video games for use with the Nintendo and Sega Genesis systems. 

Some of the titles include King of Kings, Bible Buffet and Bible Adventures. The newest game is Sunday Funday: The Ride, that gets kids excited about Sunday School and includes a karaoke section. 

While parents remain the largest chunk of Christian video game purchasers, the user market is not just relegated to children. Adults, some in their 60s and 70s have placed orders for the games, Lund said. 

There aren't any statistics on the size or growth of the Christian toy market, though it's clearly grown considerably since the first board games appeared in Christian bookstores about 15 years ago. 

However, Dick Malone, a vice president at Spring Arbor Distributors, a Michigan distributing house, said market growth is hemmed in by a limited repertoire of potential games. 

"After somebody has toy figures for Noah's Ark, how many more do you want your kids to have?" he asked. 

And at least one Christian educator said the proliferation of Bible-based toys is doing more harm than good. 

"That kind of stuff is what's wrong with Christianity right now," said Perry G. Downs, director of the doctor of education program at Trinity Evangelical Divinity School in Deerfield, Ill. 

"When you take what we say is the word of God and trivialize it into a video game you teach disregard, rather than regard, for the word of God," Downs said. 

"The Christian industry tends to mirror what is going on in the secular industry," said John Chrastka, book buyer at Logos Bookstore of Oak Park, Ill. He calls the toy revolution the "Christianization of mainstream media." 

For the past 10 years, Elgin, Ill.-based Rainfall Toys has marketed action figures, preschool toys, activity toys, puzzles, games, dolls, play sets and videos. 

Wal-Mart will carry the Holyland Heroes line in its Illinois stores to test the waters before carrying them nationwide. The figures will be available around Easter, said Keith Morris, spokesman for Wal-Mart.  

Document lad0000020011025dr2q005hj


* Christian Video Toys Come to the Rescue: Make Way for Holyland Heroes 

BERNIE MIXON -  Chicago Tribune 
981 words
5 March 1995
Buffalo News
BFNW
English
© 1995 Buffalo News.  Provided by ProQuest Information and Learning.  All rights reserved.  

To rescue heroes imperiled by villains in the make-believe world of video games, most kids would call on laser-guided missiles or at least a well-placed karate kick. 

Twelve-year-old Antoine Babicz turns to an arsenal of Bible questions. Answering them gets Moses out of a jam and shows the Egyptians a thing or two. 

Like countless adolescent boys, Antoine is enamored of his Game Boy machine, but he loads it with a game called Exodus instead of the Super Mario Brothers. In another barometer of shifting popular culture, Exodus and other games such as Super 3-D Noah's Ark are part of an emerging niche of Christian video toys and action figures that are being marketed to parents fed up with Hollywood sex and violence and ready for value in toys beyond the price tag. 

"I like action and adventure, and this is like going on an adventure in the Bible," Antoine said. "You get to go through mazes with Moses and fight the Egyptians with the Word." 

After the dust settles in other games, the ultimate aim is to be the only one left standing. Antoine seeks treasures of holy oil, the armor of God and greater faith. In Super 3-D Noah's Ark, players must regain order in the ark using food as a lure. 

The games join the more established Christian book, gift and rock music industries, which have been expanding for more than a decade. The Christian book market, for example, has grown to a nearly $3 billion industry last year from $1 billion in 1980, according to the Christian Booksellers Association. 

Bill Anderson, president of the association, said the growing interest in Christianity and "family values" will draw more parents to the market. 

"We are seeing an increasing number of baby boomers -- churched as well as unchurched -- coming into the stores looking for products to help them instill in their children qualities like honesty, integrity, respect for authority -- things based in the Scriptures," he said. 

The new action figures include the Holyland Heroes, five different sets depicting stories from the Old Testament. There's Samson and a Philistine; David and Goliath; Judas Maccabaeus and a Syrian warrior; Moses and Ramses II; and Joshua and a Canaanite. 

"We are hoping to use the Old Testament in a very sober and wise way," said David Pagani, president of Vermont-based New Ventures, which markets Holyland Heroes. "Action figures are so dominant in play patterns of young children right at the time they are supposed to be open to new ideas." 

"Parents don't have to worry about the content of these games," said Debbie Lund, general manager of Wisdom Tree of Brea, Calif., which manufactures Christian video games for use with the Nintendo and Sega Genesis systems. 

Some of the titles include King of Kings, Bible Buffet, and Bible Adventures. The newest game is Sunday Funday -- the Ride, which gets kids excited about Sunday school and includes a karaoke section. 

While parents remain the largest chunk of Christian video game purchasers, the user market is not just relegated to children. Adults, some in their 60s and 70s, have placed orders for the games, Lund said. 

There aren't any statistics on the size or growth of the Christian toy market, though it's clearly grown considerably since the first board games appeared in Christian bookstores about 15 years ago. 

However, Dick Malone, a vice president at Spring Arbor Distributors, a Michigan distributing house, said market growth is hemmed in by a limited repertoire of potential games. 

"After somebody has toy figures for Noah's Ark, how many more do you want your kids to have?" he asked. 

And at least one Christian educator says the proliferation of Bible-based toys is doing more harm than good. 

"That kind of stuff is what's wrong with Christianity right now," said Perry G. Downs, director of the doctor of education program at Trinity Evangelical Divinity School in Deerfield, Ill. 

"When you take what we say is the word of God and trivialize it into a video game you teach disregard, rather than regard, for the word of God," Downs said. 

"The Christian industry tends to mirror what is going on in the secular industry," said John Chrastka, book buyer at Logos Bookstore of Oak Park, Ill. He calls the toy revolution the "Christianization of mainstream media." 

For the past 10 years, Elgin, Ill.-based Rainfall Toys has marketed action figures, preschool toys, activity toys, puzzles, games, dolls, play sets and videos. 

Wal-Mart will carry the Holyland Heroes line in its Illinois stores to test the waters before carrying them nationwide. The figures will be available around Easter, said Keith Morris, spokesman for Wal-Mart. 

Paul and Vanessa Babicz carefully scrutinize toys their kids play with to make sure they are in line with the couple's Pentecostal beliefs. 

There wasn't much of a selection of video games to satisfy Antoine's yearning for adventure without violence until Christian video games came on the market. 

"This is a great alternative," Paul Babicz said. "There's so much junk out there, stuff totally against our beliefs." 

But critic Downs said the reason for the toy boom comes down to pure economics. 

"I do think it is another form of marketing Jesus, marketing Christianity," Downs said. "It is part of why Christianity is becoming increasingly marginalized in our society." 

Vanessa Babicz does not agree. 

"If we want kids to stay in line with the way we've raised them, then we have to compete with what the world is putting out there," she said. 

"As Christian parents, we have to find ways to keep kids going the right way. Kids can have fun and keep God in it."  

Document bfnw000020011024dr3500a2r


* Holyland Heroes take to the electronic battlefield  

SOUTHAMSTAR NETWORK
421 words
22 April 1995
Kitchener-Waterloo Record
TKWR
Final
C5
English
Copyright (c) 1995 Kitchener-Waterloo Record.  

The venture joins the more established Christian book, gift and rock-music industries, which have been expanding for more than a decade.  

Debbie Lund, general manager of Wisdom Tree of Brea, Calif., makes games for Sega Genesis, Nintendo, Game Boy and personal computer systems with intriguing names like Spiritual Warfare, Exodus and Noah's Ark.  

The idea, she said, is to offer Christian-oriented replacements for the standard cut-and-slash fare.  

Spiritual Warfare uses a modern setting in which the player encounters challenges on the way to finding the armor of God, she says. There are more than 300 screens and background Gospel music.  

Different levels are reached by answering some of the 250 biblical questions.  

But will it attract young people more familiar with Donkey Kong and Tank Commander?  

Levy Pugerude, a Grade 5 student at a suburban Edmonton school, thinks they will. He was given a chance to play Spiritual Warfare, one of a batch of computer-type games from Blessings Christian Marketplace. He rates it "good."  

"I like the color and there's lots of action. It's better than other games ...but the questions are kind of hard."  

That's OK with Levy's dad, Dan Pugerude, principal of the school and a doctor of Old Testament studies. Some theologians criticize the development of Christian games as trivializing Bible stories.  

Pugerude disagrees.  

"The church has to keep up with the times. If this game can draw a child away from one sitcom or arcade game, then it's worth it."  

He watched his son play the game and saw what was on the screen.  

"It doesn't compromise the Bible. It's a use of contemporary media and it's a little flashier."  

Levy also played with a couple of sets of Holyland Action Figures, supplied by Vermont-based New Ventures. The figures are designed to replace Power Rangers with real historical figures, says creator Dave Pagani.  

Each set, in this case David and Goliath and Sampson and a Philistine, comes with a miniature book relating the story.  

Pagani, who has been a toymaker for 25 years, saved his money and set up his own plant to pursue his new interest.  

"The toy companies rejected the idea 12 years ago. They thought it wasn't big enough."  

Pagani wants to expand into Canada, but says the French packaging requirement makes it too expensive for now.  

Levy Pugerude looks at toy Bible characters . Larry Wong, edmont journal  

Document TKWR000020060128dr4m006vb
